[package]
name = "revolt-parser"
version = "0.9.3"
edition = "2021"
license = "MIT"
authors = ["Zomatree <me@zomatree.live>", "Paul Makles <me@insrt.uk>"]
description = "Revolt Backend: Message Parser"

[dependencies]
logos = { version = "0.15" }
